name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.isocalendar.fullyear.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.leetcode.svg
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: nayakazna
          plugin_leetcode_sections: solved, skills, recent

      # - uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     filename: metrics.plugin.steam.svg
      #     base: ""
      #     plugin_steam: yes
      #     plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
      #     plugin_steam_user: 76561198343860084
      #     plugin_steam_sections: player, most-played, recently-played

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.music.svg
          base: ""
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKEN }}